apiVersion: apps/v1
kind: Deployment
metadata:
  name: db01
  namespace: vprofile
  labels:
    app: db01
    tier: db
spec:
  replicas: {{ .Values.db.replicaCount }}
  selector:
    matchLabels:
      app: db01
  template:
    metadata:
      labels:
        app: db01
        tier: db
    spec:
      imagePullSecrets:
        - name: ecr-secret
    spec:
      containers:
        - name: db01
          image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}"
          ports:
            - containerPort: {{ .Values.db.service.targetPort }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "{{ .Values.db.databasePassword }}"
            
            - name: MYSQL_DATABASE
              value: "{{ .Values.db.databaseName }}"
          livenessProbe:
            exec:
              command: 
                ["mysqladmin", "ping", "-h", "localhost", "-p{{ .Values.db.databasePassword }}"]
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 10
          readinessProbe:
            exec:
              command: 
                ["mysqladmin", "ping", "-h", "localhost", "-p{{ .Values.db.databasePassword }}"]
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 10
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/mysql
      volumes:
        - name: db-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: db01
  namespace: vprofile
  labels:
    app: db01
spec:
  selector:
    app: db01
  ports:
    - port: {{ .Values.db.service.port }}
      targetPort: {{ .Values.db.service.targetPort }}