name: Java CI

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Runner Information
        run: |
          echo "Current User:"
          whoami

          echo "Current Directory:"
          pwd

          echo "Operating System:"
          uname -a

          echo "Repository Files:"
          ls -la